### ISSUE TITLE
object code

### ISSUE THREAD

**Issue by Dskpupper** [nielslerches/common-query#7]
Hey after parsing the the query does this project does code generation? like taking the parsed expression it creates a target machine code ?

**Comment by nielslerches** [comment]
Hey.

Sorry, this library does not compile to machine code like GCC.
I guess this would be most suited for something like generating a function in C, which a user of said function could use in their own C code.

I guess another option could be to generate some C code, which would be compiled by GCC into an executable which would take a single command line argument, which the generated query would be executed on.

Is this what you're looking for?

**Comment by Dskpupper** [comment]
Hey thank you  for your reply, I appreciate it 
Ya I am looking for code generator . I need to parse Random SQL statements , obtain the parsed expression , and generate a target machine code from it. Basically perfrom a code generation. 
So if i use python  GCC library i will be able to generate the target code?

**Comment by nielslerches** [comment]
Ah okay. I think you're looking for a SQL compiler, which this library is not.

**Comment by Dskpupper** [comment]
Any sugesstions for SQL compiler? or the python librairies i can use for code generation. ( ps: pls dnt mind , I am new at this)

Thanks in advance

**Comment by nielslerches** [comment]
No worries :relaxed: 

I guess this is closest to what you're looking for? https://github.com/Legacy25/ValkyrieDB
However it might be easier to have some library generate some code you can use in your own code, like https://github.com/kyleconroy/sqlc (golang)
I haven't found any python library that turns SQL into a something you can execute straight out of the box.

Cheers.
